### ISSUE TITLE
video understanding performance

### ISSUE THREAD

**Issue by sunyoe** [EvolvingLMMs-Lab/LongVA#16]
Thank you for your inspiration about long video understanding work.
But when I test the demo with a video (which a baby is jumping and playing on the bed), and ask "what does the baby doing in the video" in chinese, I got the answer--"there are **many** girls..." (translated by chinese answer)
I’m worried that the performance about video understanding, maybe no-video-training got inherent problem about video? Such as:
1. how to identify the people in the video
2. count the number of people or things in the video

**Comment by jzhang38** [comment]
Yeah, I fully agree we still need video data at the end of the day. In LongVA, we view image-text as short data and video-text as long data. We try to clearly show the long context transfer phenomenon and that is why we did not include video training.
