### ISSUE TITLE
ValueError: Unknown model class ModelArguments(model_name_or_path='lmms-lab/LongVA-7B'

### ISSUE THREAD

**Issue by Wiselnn570** [EvolvingLMMs-Lab/LongVA#20]
I got an error when running dpo.sh. I noticed that the script's entry point is llava/train/train_dpo.py. However, when I changed it to long/train/train_dpo.py, the bug occurred.

**Comment by kcz358** [comment]
Hi, I have fixed this issue. Can you try again? We forgot to update the `get_model` with our current base_model name in the dpo training script

**Comment by Wiselnn570** [comment]
> Hi, I have fixed this issue. Can you try again? We forgot to update the `get_model` with our current base_model name in the dpo training script

Thank you, it’s working fine now. But if I need to add some video data during fine-tuning maybe to give the model new capabilities and train it together with the existing image data, how should I modify the fine-tuning script parameters? Does the current model support this type of training, or have you previously tried adding video data during fine-tuning? Thank you for your further explanation. I have already tried it, and I’m impressed by the model’s capabilities.

**Comment by kcz358** [comment]
I think you can prepare the json file just like the image, just change the `image` to `video` and add `video_path` in the args
