### ISSUE TITLE
Question about chat template

### ISSUE THREAD

**Issue by ThisisBillhe** [EvolvingLMMs-Lab/LongVA#22]
I notice that the prompt_question is 
`'<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n<image>\nWhat does this video show?<|im_end|>\n<|im_start|>assistant\n' `
when inferencing with local_demo/longva_backend.py. I wonder whether it's correct since there seem to be redundant 'im_start' and 'im_end'.

**Comment by jzhang38** [comment]
We follow Qwen2's chat template.

**Comment by ThisisBillhe** [comment]
Thanks for your reply.
