### ISSUE TITLE
pretrain error

### ISSUE THREAD

**Issue by justgogorunrun** [EvolvingLMMs-Lab/LongVA#25]
why there is error in llava_arch when run pretrain：
else:   
            error_message = """
            Something is wrong with the input shape. Most likely, you did not wrap the video input in a list:
            This is correct:
                model.generate(input_ids, images=[video_tensor],  modalities=["video"], **gen_kwargs)
            This is wrong:
                model.generate(input_ids, images=video_tensor,  modalities=["video"], **gen_kwargs)
            """
            raise ValueError(error_message)

PROMPT_VERSION=plain

BASE_RUN_NAME="llavanext-${VISION_MODEL_VERSION_CLEAN}-${LLM_VERSION_CLEAN}-mlp2x_gelu-pretrain_blip558k_plain"
echo "BASE_RUN_NAME: ${BASE_RUN_NAME}"

ACCELERATE_CPU_AFFINITY=1 torchrun --nproc_per_node="${NUM_GPUS}" --nnodes="${NNODES}" --node_rank="${RANK}" --master_addr="${ADDR}" --master_port="${PORT}" \
    longva/train/train_mem.py \
    --deepspeed scripts/zero3.json \
    --model_name_or_path ${LLM_VERSION} \
    --version ${PROMPT_VERSION} \
    --data_path /data/LongVA/llava_pretrain_data/blip_laion_cc_sbu_558k.json \
    --image_folder /data/LongVA/llava_pretrain_data/images \

**Comment by GroundMoRe** [comment]
@justgogorunrun hi, did you figure out why? I met the same problem.

**Comment by nanocm** [comment]
I encountered the same issue, too. 
Is it because of directly passing the blip_laion_cc_sbu_558k.json from liuhaotian/LLaVA-Pretrain?
